spring:
  datasource:
    url: jdbc:mysql://rdsj4q8eme71f45q4u80.mysql.rds.aliyuncs.com:3306/youyu_yungo?useUnicode=true&autoReconnect=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: youyudb1
    password: youyuDb1
    jmx-enabled: true
    test-while-idle: true
    test-on-borrow: true
    validation-query: SELECT 1
    test-on-return: false
    validation-interval: 30000
    time-between-eviction-runs-millis: 30000
    max-active: 100
    initial-size: 10
    max-wait: 10000
    remove-abandoned-timeout: 60
    min-evictable-idle-time-millis: 30000
    min-idle: 10
    log-abandoned: true
    remove-abandoned: true
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: 33b23fcff49c449b.m.cnsza.kvstore.aliyuncs.com
    port: 6379
    password: 33b23fcff49c449b:Langu123
    pool:
      max-wait: 5000
      max-active: 500
      max-idle: 8
    timeout: 1000

  jackson:
    serialization-inclusion: non_null
task:
  pool:
    size: 6
  queue:
    capacity: 20

mybatis:
  typeAliasesPackage: com.langu.wanba.core.data.domain
  configLocation: classpath:mybatis/mybatis.xml
  mapperLocations: classpath:mybatis/sql/*.xml

emchat:
  host: https://a1.easemob.com
  password: 123456
  appkey: pingke#yungo
  clientId: YXA661K68JvxEea3I4VBp7YGwA
  secret: YXA64w0Zvn8D91m2aof_0acXeGKMH3M

pay:
  host: http://api.yungo.fallchat.com
  aliUrl: /api/pay/notify/alipay
  aliVirtualUrl: /api/pay/virtual/notify/alipay
  wepayUrl: /api/pay/notify/wepay
  applePayVipUrl: https://buy.itunes.apple.com/verifyReceipt
  applePayVipUrlSandbox: https://sandbox.itunes.apple.com/verifyReceipt
  debug: false

server:
  port: 8099

switch:
  debug: false
